site_name: Bergwerk Documentation

nav:
  - Home: index.md
  - Installation: 01_installation.md
  - User Guide: 02_usage.md
  - License: 05_license.md

theme: material

site_dir: docs_html

plugins:
  - mkdocstrings

extra:
  alternate:
    - name: English
      link: ./en/ 
      lang: en
    - name: Deutsch
      link: ./de/
      lang: de